language: java
jdk:
  - openjdk15
sudo: false
env:
  global:
    - CODECOV_TOKEN="6e836c92-d895-4054-a25d-c6c707b498bc"
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -alexustmsk@gmail.com
    on_success: never # default: change
    on_failure: always # default: always